### ISSUE TITLE
Stamping database might fail because MySQL server is not available yet

### ISSUE THREAD

**Issue by fredreichbier** [NetKnights-GmbH/ubuntu#13]
I just updated privacyidea-apache2 to 3.0 and got the following error during ``apt-get dist-upgrade``:

```
Traceback (most recent call last):
  File "/opt/privacyidea/bin/pi-manage", line 1231, in <module>
    manager.run()
  File "/opt/privacyidea/local/lib/python2.7/site-packages/flask_script/__init__.py", line 417, in run
    result = self.handle(argv[0], argv[1:])
  File "/opt/privacyidea/local/lib/python2.7/site-packages/flask_script/__init__.py", line 386, in handle
    res = handle(*args, **config)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/flask_migrate/__init__.py", line 259, in upgrade
    command.upgrade(config, revision, sql=sql, tag=tag)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/command.py", line 254, in upgrade
    script.run_env()
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/script/base.py", line 427, in run_env
    util.load_python_file(self.dir, 'env.py')
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/util/pyfiles.py", line 81, in load_python_file
    module = load_module_py(module_id, path)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/util/compat.py", line 141, in load_module_py
    mod = imp.load_source(module_id, path, fp)
  File "/opt/privacyidea/lib/privacyidea/migrations/env.py", line 88, in <module>
    run_migrations_online()
  File "/opt/privacyidea/lib/privacyidea/migrations/env.py", line 79, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/runtime/environment.py", line 836, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 337, in run_migrations
    head_maintainer.update_to_step(step)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 540, in update_to_step
    self._update_version(from_, to_)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/runtime/migration.py", line 500, in _update_version
    == literal_column("'%s'" % from_))
  File "/opt/privacyidea/local/lib/python2.7/site-packages/alembic/ddl/impl.py", line 118, in _exec
    return conn.execute(construct, *multiparams, **params)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 980, in execute
    return meth(self, multiparams, params)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 273, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1099, in _execute_clauseelement
    distilled_params,
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1174, in _execute_context
    e, util.text_type(statement), parameters, None, None
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1458, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 296, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1169, in _execute_context
    conn = self._revalidate_connection()
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 446, in _revalidate_connection
    self.__connection = self.engine.raw_connection(_connection=self)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2259, in raw_connection
    self.pool.unique_connection, _connection
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2235, in _wrap_pool_connect
    util.reraise(*sys.exc_info())
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 2228, in _wrap_pool_connect
    return fn()
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 365, in unique_connection
    return _ConnectionFairy._checkout(self)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 822, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 554, in checkout
    rec = pool._do_get()
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 1346, in _do_get
    return self._create_connection()
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 370, in _create_connection
    return _ConnectionRecord(self)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 499, in __init__
    self.__connect(first_connect_check=True)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/pool.py", line 701, in __connect
    connection = pool._invoke_creator(self)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 437, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/MySQLdb/__init__.py", line 81, in Connect
    return Connection(*args, **kwargs)
  File "/opt/privacyidea/local/lib/python2.7/site-packages/MySQLdb/connections.py", line 193, in __init__
    super(Connection, self).__init__(*args, **kwargs2)
sqlalchemy.exc.OperationalError: (_mysql_exceptions.OperationalError) (2013, "Lost connection to MySQL server at 'reading initial communication packet', system error: 104") [SQL: u"UPDATE alembic_version SET version_num='cb6d7b7bae63' WHERE alembic_version.version_num = 'a63df077051a'"] (Background on this error at: http://sqlalche.me/e/e3q8)
```

The reason is probably that this line:
https://github.com/NetKnights-GmbH/ubuntu/blob/8835cd2ee978ccdbbd4a3bcca75cdb7a2adfe923/debian_server/privacyidea-apache2.postinst#L89

does not wait until the MySQL server is available again?

**Comment by cornelinux** [comment]
@NuvandaPV should we change this to systemctl or something that is working on 16.04 and 18.04?

**Comment by NuvandaPV** [comment]
That seems like a good idea, however i don't think that by itself will solve this issue, since MySQL spinning up will still happen asynchronously,afaik.

**Comment by cornelinux** [comment]
I never experienced this issue. 

The restart is done due to the previous line, where we set the barracuda config thingy.
This is rather "old", so I guess most installations will already have the barracuda setting. 
We could maybe not solve but mitigate this problem in that, that we first check, if the barracuda setting exist, and only if it does not exist, add it and restart the mysql server - since in most cases restarting the server during an dist-upgrade will not be necessary.
